// generated by Fast Light User Interface Designer (fluid) version 1.0300

#ifndef fltkgui_h
#define fltkgui_h
#include <FL/Fl.H>
#include <SI/Si_Button.H>
#include "sqlite3.h"
#include "functions.h"
#include "door.h"
#include <iostream>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Choice.H>
using namespace std;

class Resize_Window : public Fl_Double_Window {
public:
  Resize_Window(int W, int H, const char *l = 0);
  Resize_Window(int X, int Y, int W, int H, const char *l = 0);
  void resize(int X,int Y,int W,int H);
};
extern Resize_Window *wnd_main;
#include <FL/Fl_Group.H>
extern Fl_Group *grp_Sidebar;
#include <FL/Fl_Input.H>
extern void cb_SearchTextChanged(Fl_Input*, void*);
extern Fl_Input *ipt_style;
extern Fl_Input *ipt_size;
extern Fl_Input *ipt_material;
extern Fl_Input *ipt_glass_style;
#include <FL/Fl_Browser.H>
extern void cb_MostUsedItemSelected(Fl_Browser*, void*);
extern Fl_Browser *bsr_MostUsed;
extern void cb_grid(Fl_Group*, void*);
extern Fl_Group *grp_DoorGrid;
#include <FL/Fl_Scroll.H>
extern Fl_Scroll *scroll_DoorGrid;
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Pack.H>
#include <FL/Fl_Menu_Button.H>
#include <FL/Fl_Check_Button.H>
#include <FL/Fl_Text_Editor.H>
Fl_Double_Window* make_door_info_dialog_old(Door door);
extern Fl_Input *txt_LocationName;
#include <FL/Fl_Choice.H>
extern Fl_Choice *lst_DoorSize;
extern Fl_Choice *lst_DoorSwing;
extern Fl_Choice *lst_JambSize;
extern Fl_Choice *lst_JambMaterial;
extern Fl_Choice *lst_Sill;
extern void cb_update(Fl_Check_Button*, void*);
extern Fl_Check_Button *chk_BrickMoldYes;
extern Fl_Check_Button *chk_BrickMoldNo;
extern Fl_Check_Button *chk_DeadBoltYes;
extern Fl_Check_Button *chk_DeadBoltNo;
extern Fl_Choice *lst_HingeColor;
#include <FL/Fl_Value_Output.H>
extern Fl_Value_Output *val_Cost;
#include <FL/Fl_Value_Input.H>
extern void cb_markup(Fl_Value_Input*, void*);
extern Fl_Value_Input *val_Markup;
extern Fl_Value_Input *val_Price;
extern Fl_Text_Editor *txt_Notes;
extern void cb_PrintClicked(Fl_Button*, void*);
extern void cb_CancelClicked(Fl_Button*, void*);
#include <FL/Fl_Output.H>
extern Fl_Output *opt_DoorStyle;
extern Fl_Output *opt_DoorMaterial;
extern Fl_Output *opt_GlassStyle;
extern Fl_Output *opt_Design;
extern Fl_Box *boxDoorImage;
Fl_Double_Window* make_door_info_dialog(Door door);
extern Fl_Group *grp_PrintGroup;
extern Fl_Box *opt_CompanyInfo;
extern Fl_Box *box_Print_DoorImage;
extern Fl_Box *opt_Print_LocationName;
extern Fl_Box *opt_Print_DoorSize;
extern Fl_Box *opt_Print_DoorMaterial;
extern Fl_Box *opt_Print_DoorStyle;
extern Fl_Box *opt_Print_DoorSwing;
extern Fl_Box *opt_Print_JambSize;
extern Fl_Box *opt_Print_JambMaterial;
extern Fl_Box *opt_Print_Sill;
extern Fl_Box *opt_Print_Brickmold;
extern Fl_Box *opt_Print_DeadBolt;
extern Fl_Box *opt_Print_GlassStyle;
extern Fl_Box *opt_Print_Price;
extern Fl_Box *opt_Print_HingeColor;
extern void cb_Preview_PrintClicked(Fl_Button*, void*);
extern void cb_Preview_CancelClicked(Fl_Button*, void*);
extern void cb_Preview_MakePDFClicked(Fl_Button*, void*);
Fl_Double_Window* make_print_dialog();
void infoDialogReady(); 
#endif
